# Generated by Django 3.2.5 on 2021-07-15 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='registration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=20)),
                ('frist_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
                ('email_address', models.EmailField(max_length=254)),
                ('phone_no', models.CharField(max_length=11)),
                ('road_no', models.CharField(max_length=10)),
                ('country', models.CharField(choices=[('Bangladesh', 'Bangladesh'), ('Bangladesh', 'Bangladesh'), ('India', 'India'), ('Pakistan', 'Pakistan'), ('NewYork', 'NewYork')], max_length=50)),
            ],
        ),
    ]
