# Generated by Django 3.2.5 on 2021-07-15 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='country',
            field=models.CharField(choices=[('', '-----Country Select -----'), ('Bangladesh', 'Bangladesh'), ('India', 'India'), ('Pakistan', 'Pakistan'), ('NewYork', 'NewYork')], max_length=50),
        ),
    ]
